name: Deploy to GitHub Pages

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm test

  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Set the pathname
        run: |
          echo "base_path=/${{ env.GITHUB_REPOSITORY_NAME_PART }}/${{ env.GITHUB_REF_SLUG }}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - name: Next export
        env:
          NEXT_PUBLIC_BASE_PATH: ${{ env.base_path }}
        run: npm run export
      - name: Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          destination_dir: ${{ env.GITHUB_REF_SLUG }}
